name: winr
description: "A win rate calculator"
publish_to: 'none'
version: 1.0.4+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  loading_animation_widget: ^1.3.0
  sqflite: ^2.4.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  timeago: ^3.7.1
  shimmer: ^3.0.0
  path: ^1.9.1
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2
  flutter_hooks: ^0.21.3+1
  package_info_plus: ^8.3.1
  hooks_riverpod: ^2.5.1
  smooth_page_indicator: ^1.2.1
  new_version_plus: ^0.1.1
  connectivity_plus: ^6.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  freezed: ^2.4.5
  build_runner: ^2.4.8
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets: 
    - assets/icons/
    - assets/images/