name: winr
description: "A win rate calculator"
publish_to: 'none'
version: 1.0.9+9

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  loading_animation_widget: ^1.3.0
  sqflite: ^2.4.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  timeago: ^3.7.1
  shimmer: ^3.0.0
  path: ^1.9.1
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2
  flutter_hooks: ^0.21.3+1
  package_info_plus: ^8.3.1
  hooks_riverpod: ^2.5.1
  smooth_page_indicator: ^1.2.1
  new_version_plus: ^0.1.1
  connectivity_plus: ^7.0.0
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  freezed: ^3.2.3
  build_runner: ^2.8.0
  analyzer: ^8.1.1
  analyzer_plugin: ^0.13.7
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets: 
    - assets/icons/
    - assets/images/